### ISSUE TITLE
callback call failing if userModelClass() not set in Panel Provider

### ISSUE THREAD

**Issue by jd-klauslila** [DutchCodingCompany/filament-socialite#109]
Hello,

Just noticed that this commit:
https://github.com/DutchCodingCompany/filament-socialite/commit/757e7c2096c33d4cddd53b7218802f27c9602af8

In the file:
`src/Traits/Models.php`

That changes this
    `protected string $userModelClass = User::class;` 
to this:
    `protected ?string $userModelClass = null;`
    
makes `->userModelClass(\App\Models\User::class)` in Panel Provider mandatory (not optional as should be).

If not set, the callback call will fail with this error:
**_Class name must be a valid object or a string_**
@ \vendor\dutchcodingcompany\filament-socialite\src\Traits\Callbacks.php :118

Can you check it?

Thank you

![error](https://github.com/user-attachments/assets/b7f9abce-a3d8-41ec-90ae-aa5102140d72)

**Comment by bert-w** [comment]
Fixed in v2.2.1
