### ISSUE TITLE
`Route [] not defined` exception is thrown when redirecting to login after authentication 

### ISSUE THREAD

**Issue by caendesilva** [DutchCodingCompany/filament-socialite#18]
## Description

Just installed this, and after logging in with GitHub and getting redirected to the callback route, I get an RouteNotFoundException. The error occurs on the following line:

https://github.com/DutchCodingCompany/filament-socialite/blob/2f35b8e663415256a6bb571631349804ef02c3d7/src/Http/Controllers/SocialiteLoginController.php#L58

## Suspected cause
As far as I can tell, there is no default configuration setting with that key in Filament, causing an exception due to Laravel trying to find a route named `null`. I suspect that this is a mistake and you are not wanting to use the configuration at all, but instead use the route name.

### Patching existing installations:
I patched this on my installation by adding the following to my `config/filament.php` file:

```diff
    'auth' => [
        'guard' => env('FILAMENT_AUTH_GUARD', 'web'),
        'pages' => [
            'login' => \JeffGreco13\FilamentBreezy\Http\Livewire\Auth\Login::class,
        ],
+       'login' => 'filament.auth.login'
    ],
```

> Note that it's since the config key shares is the same as the route key I suspect that you are not actually intending to use the config at all

### Fixing the source #‎1

Changing the following in the controller would fix this:

```diff
    protected function redirectToLogin(string $message): RedirectResponse
    {
        // Redirect back to the login route with an error message attached
-       return redirect()->route(config('filament.auth.login'))
+       return redirect()->route('filament.auth.login')

        // ...
    }
```

### Fixing the source #‎2

Or, if you do want it to be configurable, I would suggest using a config key for this package's config file, as you have control over it. In this case, I would personally add the default route as a fallback.

```diff
    protected function redirectToLogin(string $message): RedirectResponse
    {
        // Redirect back to the login route with an error message attached
-       return redirect()->route(config('filament.auth.login'))
+       return redirect()->route(config('filament-socialite.login_route_name', 'filament.auth.login'))

        // ...
    }
```

## Summary

I hope this issue report helps. I'm happy to submit a PR with either of the the options if you'd like.

Thanks for making an otherwise super easy to use package! Cheers!

**Comment by caendesilva** [comment]
The way I encountered this may actually be partly an XY problem because I shouldn't be redirected with an error message at all when creating an account. As it is now, I need to hit the log in button twice. This part of the problem way be entirely on my side though, I'm just thinking out loud.

**Comment by marcoboers** [comment]
I will be able to look into this on Monday. Feel free to put in a PR if you believe it is an issue with the package.

**Comment by caendesilva** [comment]
> I will be able to look into this on Monday. Feel free to put in a PR if you believe it is an issue with the package.

No worries! There's no rush in open source! I'll see about making a PR :)

**Comment by caendesilva** [comment]
I also encountered this when `SocialiteLoginController::isUserAllowed` returns false.
