### ISSUE TITLE
Support for User model with SoftDeletes

### ISSUE THREAD

**Issue by RixzZ** [DutchCodingCompany/filament-socialite#22]
Currently if you enable softdeleting on your User model, when you try login using socialite to log in to the deleted user, it throws and error:
```
Illuminate\Auth\SessionGuard::login(): Argument #1 ($user) must be of type Illuminate\Contracts\Auth\Authenticatable, null given, called in /var/www/vendor/dutchcodingcompany/filament-socialite/src/Http/Controllers/SocialiteLoginController.php
```

Is there a way to make Socilite check for softdeleted users and throw an error page if it exists (since it can't be created again either)?

**Comment by bert-w** [comment]
In v1.3.0 you should be able to provide your own resolution logic by creating a custom SocialiteUser class.

See this new section in the readme:
https://github.com/DutchCodingCompany/filament-socialite?tab=readme-ov-file#change-how-a-socialite-user-is-created-or-retrieved
