### ISSUE TITLE
Is it possible to enable the Laravel 8 support?

### ISSUE THREAD

**Issue by oyepez003** [DutchCodingCompany/filament-socialite#3]
Hi, I trying to use this library in my Filament project but I'm using Larave 8.x, and Composer returns the next dependency error:

```bash
Problem 1
    - Root composer.json requires dutchcodingcompany/filament-socialite ^0.1.1 -> satisfiable by dutchcodingcompany/filament-socialite[0.1.1].
    - dutchcodingcompany/filament-socialite 0.1.1 requires illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
```

Why is your package requiring the last version illuminate/contracts ^9.0 if Laravel Socialite works with Laravel 6 and older?

You can see the Laravel Socialite dependency [here](https://github.com/laravel/socialite/blob/5f6bf50ddb296e559bc7710553b166d28a4c709e/composer.json#L21):

```json
{
...
   "illuminate/contracts": "^6.0|^7.0|^8.0|^9.0",
...
```

Maybe if you can update the dependency in this package, we can use it in the Laravel 8.x version even.

```json
{
...
   "illuminate/contracts": "^8.0|^9.0",
...
```

Regards.

**Comment by marcoboers** [comment]
Since the filament admin panel supports Laravel 8, I will add support for Laravel 8 as well.
