### ISSUE TITLE
documentation fixes: source link and FilamentSocialite::setCreateUserCallback example

### ISSUE THREAD

**Issue by wivaku** [DutchCodingCompany/filament-socialite#31]
The following has issues:

https://filamentphp.com/plugins/socialite#changing-how-a-socialite-user-is-created-or-retrieved

1) `)` is missing at the end of the code snippet
2) referring to `SocialiteUserContract` but the `use` is referring to `UserContract`
3) `FilamentSocialite $socialite` causes error (similar to #25): 

```
App\Providers\AppServiceProvider::App\Providers\{closure}(): Argument #2 ($socialite) must be of type DutchCodingCompany\FilamentSocialite\Facades\FilamentSocialite, DutchCodingCompany\FilamentSocialite\FilamentSocialite given,
```

And: the [`See [FilamentSocialite.php]`](https://filamentphp.com/plugins/src/FilamentSocialite.php) links refer to the incorrect URL.
Should be (I think):
https://github.com/DutchCodingCompany/filament-socialite/blob/main/src/FilamentSocialite.php

**Comment by bert-dcc** [comment]
Fixed in upcoming release (for Filament v3) https://github.com/DutchCodingCompany/filament-socialite/pull/46
