### ISSUE TITLE
Feature request: Add a notification banner or validation error message when user's email domain is not whitelisted

### ISSUE THREAD

**Issue by caendesilva** [DutchCodingCompany/filament-socialite#39]
So I just got confused why I couldn't log into my app. Nothing at all happened after logging in with my social provider, just got redirected back to the login page. Then realized I had a typo in the domain allowlist. I think a notification banner or a validation error message would be really nice to have here, maybe saying something like "Sorry, that email provider is not enabled for this application". Bonus points if it's configurable!

Thanks for a super useful package!

**Comment by dododedodonl** [comment]
The error described is a configuration error, so not a user facing error. For that reason, it does not seem logical to add user facing error messages. These errors can already be found in the laravel.log file.
