### ISSUE TITLE
Driver [zoom] not supported.

### ISSUE THREAD

**Issue by MarJose123** [DutchCodingCompany/filament-socialite#41]
I tried Socialite for Zoom but its not working.
https://socialiteproviders.com/Zoom/#installation-basic-usage

My config for the `services` and `filament-socialite`

```php
/// ...... other services
 'zoom' => [
        'client_id' => env('ZOOM_CLIENT_ID'),
        'client_secret' => env('ZOOM_CLIENT_SECRET'),
        'redirect' => env('ZOOM_REDIRECT_URI')
    ],
```
```php
//.. other filament-socialite parameter.
  'providers' => [
        'github' => [
            'label' => 'GitHub',
        ],
        'zoom' => [
            'label' => 'Zoom',
        ]
    ],
```

it seems that it is only working for the defined by the laravel socialite.

**Comment by dododedodonl** [comment]
Please ensure socialite is working outside if the filament plugin. If problems persist and a bug is identified that can be reproduced, please open a new issue.
