### ISSUE TITLE
Localization strings need Package Namespace

### ISSUE THREAD

**Issue by gn0rt0n** [DutchCodingCompany/filament-socialite#44]
Example:

`dutchcodingcompany/filament-socialite/src/Http/Controllers/SocialiteLoginController.php
162:            return $this->redirectToLogin('auth.registration-not-enabled');
`

should be:

`
dutchcodingcompany/filament-socialite/src/Http/Controllers/SocialiteLoginController.php
162:            return $this->redirectToLogin('filament-socialite::auth.registration-not-enabled');
`

Without this, you will not get proper registration failure messages when using this with other packages like Breezy. There are probably other places this needs to be changed. I didn't have time to create a PR. Sorry ☹️

**Comment by bert-dcc** [comment]
Fixed in upcoming release (for Filament v3) https://github.com/DutchCodingCompany/filament-socialite/pull/46
