### ISSUE TITLE
FilamentSocialitePlugin::make()->setDashboardRouteName doesn't work

### ISSUE THREAD

**Issue by plantjes** [DutchCodingCompany/filament-socialite#54]
I have multiple panels and in one panel I did set a different dashboard route with setDashboardRouteName, but this doesn't work.
It only works if I remove the line 45 on: src/FilamentSocialitePlugin.php

```php
$this->setDashboardRouteName("filament.{$panel->getId()}.pages.dashboard");
``` 
Is there a fix for this issue?

**Comment by dododedodonl** [comment]
@plantjes could you test if PR #56 fixes the issue for you?

**Comment by plantjes** [comment]
@dododedodonl Thank you, the fix is working.
