### ISSUE TITLE
Twitter Provider : Call to undefined method with

### ISSUE THREAD

**Issue by aeq-dev** [DutchCodingCompany/filament-socialite#55]
Hello,
I'm trying to setup twitter provider, I've set twitter keys, so when I click on twitter button and error appears : 
`Call to undefined method Laravel\Socialite\One\TwitterProvider::with()`

**Comment by dododedodonl** [comment]
For now, this package only supports oauth2. I'll amend the readme.

**Comment by aeq-dev** [comment]
Okey! thanks
I think this feature is not available for free account twitter developer, I mean get user email on login
