### ISSUE TITLE
Q: new user

### ISSUE THREAD

**Issue by ekandreas** [DutchCodingCompany/filament-socialite#6]
Hi!
(not possible to apply for a question in this repo, 404)

How is the auth create account supposed to work? When setting this up it redirects to a member page but the user isn't authenticated after a correct Google approval. Am I missing something here? Supposed to setup a receiving page to create the account and make it a valid login via auth() ?

**Comment by marcoboers** [comment]
Sorry for the wrong link. It should lead to the discord: https://discord.com/channels/883083792112300104/962299008259342366

Did you set `'registration' => true` in the config?

**Comment by ekandreas** [comment]
Yes, the setting is set to true.
