### ISSUE TITLE
Force select_account

### ISSUE THREAD

**Issue by Issa-projects** [DutchCodingCompany/filament-socialite#66]
Hi,
I am trying to use socialite Microsoft provider. It works fine with login (when I am not logged in to Microsoft in browser, or when logged in with same tenant). My issue is that I cannot force select_account, which could be done easily if I can add prompt=select_account, which is supported in the socialite provider - >with method. Why this doesn't work now?

**Comment by bramr94** [comment]
Do you mean this feature https://socialiteproviders.com/Microsoft/#tenant-details?

**Comment by niekbr** [comment]
I think it's about optional parameters, more general for laravel socialite: https://laravel.com/docs/10.x/socialite#optional-parameters

**Comment by Issa-projects** [comment]
Yes I meant the optional parameters. There is no way to include any parameters in the request
