### ISSUE TITLE
Redirect doesn't work with Telegram provider

### ISSUE THREAD

**Issue by punyflash** [DutchCodingCompany/filament-socialite#95]
```
DutchCodingCompany\FilamentSocialite\Http\Controllers\SocialiteLoginController::redirectToProvider(): Return value must be of type Illuminate\Http\RedirectResponse, string returned
```

There is not always redirect response for returns in controller, [Telegram](https://github.com/SocialiteProviders/Telegram) provider returns plain html to display login button

**Comment by bert-w** [comment]
I dont know what the implementation should be; the `redirect()` function of the Socialite driver requires a `RedirectResponse`. Feel free to submit a PR.
